<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <base href="/">
    <title><?= SITE_NAME; ?></title>

    <link rel="stylesheet" href="<?= URL.'assets/uikit/dist/css/uikit.min.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/animate.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/aos.css' ?>">
</head>
<body>
<div class="uk-section uk-section-muted uk-position-relative uk uk-height-viewport">
    <div class="uk-position-center " style="width: 400px">
        <div class="">
                <label for="username" class="uk-form-label"></label>
                <div class="uk-inline uk-width-1-1">
                    <span class="uk-form-icon" uk-icon="icon: pencil"></span>
                    <input class="uk-input" id="username" name="username" type="text">
                </div>
            </div>
            <div class="uk-margin">
                <label for="password" class="uk-form-label"></label>
                <div class="uk-inline uk-width-1-1">
                    <span class="uk-form-icon" uk-icon="icon: lock"></span>
                    <input class="uk-input" type="text">
                </div>
            </div>
    </div>
</div>

<script src="<?= URL.'assets/js/jquery.min.js';?>"></script>
<script src="<?= URL.'assets/uikit/dist/js/uikit.min.js';?>"></script>
<script src="<?= URL.'assets/uikit/dist/js/uikit-icons.min.js';?>"></script>
<link rel="stylesheet" href="<?= URL.'/assets/js/aos.js' ?>">
</body>
</html>