<h1 class="uk-heading-line uk-text-left">
<span>Gestion des formations</span>
</h1>
<div>
        <div uk-grid>
            <div class="uk-width-auto@m uk-flex-last@m" id="rightNav">
                <ul class="uk-tab-right" uk-tab="connect: #component-tab-right; animation: uk-animation-fade">
                    <li><a href="#">Formations enregistrées</a></li>
                    <li><a href="#">Ajouter une formation</a></li>
                    <li><a href="#">Paramètre</a></li>
                </ul>
            </div>
            <div class="uk-width-expand@m">
                <ul id="component-tab-right" class="uk-switcher">
                    <li>
                        <div>
                            <h4>Toutes les formations</h4>
                            <div class="uk-alert uk-alert-danger" uk-alert>
                                <p>Pas de formation enregistrée</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <h4>Ajouter un nouveau module de formation</h4>
                        <div>
                            <form id="frmAddFormation" enctype="multipart/form-data" novalidate>
                                <div class="uk-margin">
                                    <label for="" class="uk-form-label">Intitulé du cours</label>
                                    <input type="text" id="intitule" class="uk-input">
                                </div>
<!--                                <div class="uk-margin">-->
<!--                                    <label for="" class="uk-form-label">Image intro</label>-->
<!--                                    <input type="file" id="intitule" class="uk-input">-->
<!--                                </div>-->
                                <div class="uk-margin">
                                    <label for="" class="uk-form-label">Thème</label>
                                    <select class="uk-select" name="" id="theme_form"></select>
                                </div>
                                <div class="uk-margin">
                                    <div class="uk-inline">
                                        <label for="prix">Coût de la fomation</label>
                                        <input type="text" name="prix" id="prix" class="uk-input uk-form-width-small">
                                        (F CFA)
                                    </div>
                                    <div class="uk-inline">
                                        <label for="prix">Image d'introduction</label>
                                        <input type="file" name="image_form" id="image_form" class="uk-file">
                                    </div>
                                </div>
                                <div class="uk-margin">
                                    <label for="" class="uk-form-label">Courte description</label>
                                    <textarea name="" id="description" class="uk-textarea"></textarea>
                                </div>
                                <div class="uk-margin">
                                    <label for="" class="uk-form-label">Préréquis</label>
                                    <textarea name="" id="prerequis" class="uk-textarea"></textarea>
                                </div>
                                <div class="uk-margin uk-text-right">
                                    <button type="submit" class="uk-button uk-button-small uk-button-primary">Enregistrer</button>
                                </div>
                            </form>
                        </div>
                    </li>
                    <li>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur, sed do eiusmod.</li>
                </ul>
            </div>
        </div>
</div>

<script>
    CKEDITOR.replaceAll(['description', 'prerequis']);
</script>

<script src="<?= URL.'public/admin/js/app.js'; ?>"></script>
<script src="<?= URL.'public/admin/js/formations.js'; ?>"></script>