<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <base href="<?= URL; ?>">
    <title><?= SITE_NAME; ?></title>

    <link rel="stylesheet" href="<?= URL.'assets/uikit/dist/css/uikit.min.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/animate.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/aos.css' ?>">

    <link rel="stylesheet" href="<?= URL.'public/admin/css/main.css' ?>">
    <script src="<?= URL.'assets/js/jquery.min.js';?>"></script>
</head>
<body>
<div class="uk-flex uk-grid uk-grid-collapse uk-grid-small" uk-grid>
    <div class="left-fixed-sidenav  uk-card uk-card-secondary uk-card-body uk-card-small uk-padding-remove uk-position-fixed uk-position-top-left uk-width-1-5 uk-height-viewport">
        <?php require_once 'menu.phtml'; ?>
    </div>
    <div class="uk-width-4-5 uk-position-top-right uk-padding-small">
        <?= $output; ?>
    </div>
</div>

<script src="<?= URL.'assets/uikit/dist/js/uikit.min.js';?>"></script>
<script src="<?= URL.'assets/uikit/dist/js/uikit-icons.min.js';?>"></script>
<link rel="stylesheet" href="<?= URL.'/assets/js/aos.js' ?>">
</body>
</html>