-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 02:34:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema elearningdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elearningdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elearningdb` DEFAULT CHARACTER SET utf8 ;
USE `elearningdb` ;

-- -----------------------------------------------------
-- Table `elearningdb`.`themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`themes` (
  `idTheme` INT NOT NULL AUTO_INCREMENT,
  `intituleTh` VARCHAR(200) NULL,
  `statusTh` ENUM('on', 'off') NULL DEFAULT 'on',
  PRIMARY KEY (`idTheme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`moduleFormations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`moduleFormations` (
  `idModuleForm` INT NOT NULL AUTO_INCREMENT,
  `intituleForm` VARCHAR(200) NULL,
  `descriptionForm` MEDIUMTEXT NULL,
  `prerequis` MEDIUMTEXT NULL,
  `prix` INT NULL,
  `image` VARCHAR(255) NULL,
  `dateAjoutForm` DATE NULL,
  `statusForm` ENUM('on', 'off') NULL DEFAULT 'on',
  `themes_idTheme` INT NOT NULL,
  PRIMARY KEY (`idModuleForm`),
  INDEX `fk_moduleFormations_themes_idx` (`themes_idTheme` ASC),
  CONSTRAINT `fk_moduleFormations_themes`
    FOREIGN KEY (`themes_idTheme`)
    REFERENCES `elearningdb`.`themes` (`idTheme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`sessionFormation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`sessionFormation` (
  `idSessionForm` INT NOT NULL AUTO_INCREMENT,
  `sessionNom` VARCHAR(50) NULL,
  `dateDebutSession` DATE NULL,
  `dateFinSession` DATE NULL,
  `statusSession` ENUM('à venir', 'en cours', 'terminer') NULL DEFAULT 'à venir',
  `moduleFormations_idModuleForm` INT NOT NULL,
  PRIMARY KEY (`idSessionForm`),
  INDEX `fk_sessionFormation_moduleFormations1_idx` (`moduleFormations_idModuleForm` ASC),
  CONSTRAINT `fk_sessionFormation_moduleFormations1`
    FOREIGN KEY (`moduleFormations_idModuleForm`)
    REFERENCES `elearningdb`.`moduleFormations` (`idModuleForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`apprenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`apprenants` (
  `idApprenant` INT NOT NULL AUTO_INCREMENT,
  `nomApp` VARCHAR(45) NULL,
  `prenomsApp` VARCHAR(100) NULL,
  `contactApp` VARCHAR(45) NULL,
  `emailApp` VARCHAR(150) NULL,
  `pseudoApp` VARCHAR(45) NULL,
  `dateInscripApp` DATETIME NULL,
  `reception_new` ENUM('on', 'off') NULL,
  `pays` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `dateNaissance` DATE NULL,
  `niveauEtude` VARCHAR(45) NULL,
  `dernierDiplome` VARCHAR(45) NULL,
  PRIMARY KEY (`idApprenant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`inscriptionFormation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`inscriptionFormation` (
  `idSuivreFormation` INT NOT NULL AUTO_INCREMENT,
  `etatPaiement` ENUM('payé', 'non payé') NULL DEFAULT 'non payé',
  `dateInscription` DATETIME NULL,
  `datePaiement` DATETIME NULL,
  `moyenPaiement` VARCHAR(200) NULL,
  `sessionFormation_idSessionForm` INT NOT NULL,
  `apprenants_idApprenant` INT NOT NULL,
  PRIMARY KEY (`idSuivreFormation`),
  INDEX `fk_inscriptionFormation_sessionFormation1_idx` (`sessionFormation_idSessionForm` ASC),
  INDEX `fk_inscriptionFormation_apprenants1_idx` (`apprenants_idApprenant` ASC),
  CONSTRAINT `fk_inscriptionFormation_sessionFormation1`
    FOREIGN KEY (`sessionFormation_idSessionForm`)
    REFERENCES `elearningdb`.`sessionFormation` (`idSessionForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscriptionFormation_apprenants1`
    FOREIGN KEY (`apprenants_idApprenant`)
    REFERENCES `elearningdb`.`apprenants` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`formateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`formateurs` (
  `idFormateur` INT NOT NULL AUTO_INCREMENT,
  `nomForm` VARCHAR(45) NULL,
  `prenomsForm` VARCHAR(100) NULL,
  `emailForm` VARCHAR(130) NULL,
  `specialites` TINYTEXT NULL,
  `contactForm` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `dateAjoutForm` VARCHAR(45) NULL,
  `statusForm` ENUM('on', 'off') NULL DEFAULT 'on',
  PRIMARY KEY (`idFormateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`enseignemerFormation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`enseignemerFormation` (
  `idEnseignerForm` INT NOT NULL AUTO_INCREMENT,
  `formateurs_idFormateur` INT NOT NULL,
  `sessionFormation_idSessionForm` INT NOT NULL,
  `noteFinale` INT NULL,
  PRIMARY KEY (`idEnseignerForm`),
  INDEX `fk_enseignerFormation_formateurs1_idx` (`formateurs_idFormateur` ASC),
  INDEX `fk_enseignerFormation_sessionFormation1_idx` (`sessionFormation_idSessionForm` ASC),
  CONSTRAINT `fk_enseignerFormation_formateurs1`
    FOREIGN KEY (`formateurs_idFormateur`)
    REFERENCES `elearningdb`.`formateurs` (`idFormateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enseignerFormation_sessionFormation1`
    FOREIGN KEY (`sessionFormation_idSessionForm`)
    REFERENCES `elearningdb`.`sessionFormation` (`idSessionForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`contenuModuleForm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`contenuModuleForm` (
  `idContenuModuleForm` INT NOT NULL AUTO_INCREMENT,
  `numChapitre` INT NULL,
  `titre` TINYTEXT NULL,
  `introTextContenu` MEDIUMTEXT NULL,
  `introVideoContenu` VARCHAR(255) NULL,
  `contenu` LONGTEXT NULL,
  `statusContenu` ENUM('redaction', 'en attente', 'publié') NULL DEFAULT 'redaction',
  `enseignemerFormation_idEnseignerForm` INT NOT NULL,
  PRIMARY KEY (`idContenuModuleForm`),
  INDEX `fk_contenuModuleForm_enseignemerFormation1_idx` (`enseignemerFormation_idEnseignerForm` ASC),
  CONSTRAINT `fk_contenuModuleForm_enseignemerFormation1`
    FOREIGN KEY (`enseignemerFormation_idEnseignerForm`)
    REFERENCES `elearningdb`.`enseignemerFormation` (`idEnseignerForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`testsModuleForm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`testsModuleForm` (
  `idTest` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numTest` INT NULL,
  `dateDebutTest` DATETIME NULL,
  `dateFinTest` DATETIME NULL,
  `noteTotalTest` VARCHAR(45) NULL,
  `statusTests` ENUM('en attente', 'en cours', 'terminé') NULL DEFAULT 'en attente',
  `contenuModuleForm_idContenuModuleForm` INT NOT NULL,
  PRIMARY KEY (`idTest`),
  INDEX `fk_testsModuleForm_contenuModuleForm1_idx` (`contenuModuleForm_idContenuModuleForm` ASC),
  CONSTRAINT `fk_testsModuleForm_contenuModuleForm1`
    FOREIGN KEY (`contenuModuleForm_idContenuModuleForm`)
    REFERENCES `elearningdb`.`contenuModuleForm` (`idContenuModuleForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`questions` (
  `idQuestion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numQuestion` INT NULL,
  `typeQuestion` VARCHAR(200) NULL,
  `libelleQuestion` TINYTEXT NULL,
  `noteQuestion` VARCHAR(45) NULL,
  `testsModuleForm_idTest` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idQuestion`),
  INDEX `fk_questions_testsModuleForm1_idx` (`testsModuleForm_idTest` ASC),
  CONSTRAINT `fk_questions_testsModuleForm1`
    FOREIGN KEY (`testsModuleForm_idTest`)
    REFERENCES `elearningdb`.`testsModuleForm` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`propositions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`propositions` (
  `idProposition` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `libelleProposition` VARCHAR(255) NULL,
  `reponse` TINYINT ZEROFILL NULL DEFAULT 0,
  `questions_idQuestion` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProposition`),
  INDEX `fk_propositions_questions1_idx` (`questions_idQuestion` ASC),
  CONSTRAINT `fk_propositions_questions1`
    FOREIGN KEY (`questions_idQuestion`)
    REFERENCES `elearningdb`.`questions` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`suiviApprenant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`suiviApprenant` (
  `idSuiviApprenant` INT NOT NULL AUTO_INCREMENT,
  `numChapContenu` INT NULL,
  `statusCours` ENUM('en attente', 'en cours', 'terminé') NULL DEFAULT 'en attente',
  `numChapTest` INT NULL,
  `statusTest` ENUM('en attente', 'en cours', 'terminé') NULL DEFAULT 'en attente',
  `noteTest` VARCHAR(45) NULL,
  `apprenants_idApprenant` INT NOT NULL,
  `contenuModuleForm_idContenuModuleForm` INT NOT NULL,
  `testsModuleForm_idTest` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idSuiviApprenant`),
  INDEX `fk_suiviApprenant_apprenants1_idx` (`apprenants_idApprenant` ASC),
  INDEX `fk_suiviApprenant_contenuModuleForm1_idx` (`contenuModuleForm_idContenuModuleForm` ASC),
  INDEX `fk_suiviApprenant_testsModuleForm1_idx` (`testsModuleForm_idTest` ASC),
  CONSTRAINT `fk_suiviApprenant_apprenants1`
    FOREIGN KEY (`apprenants_idApprenant`)
    REFERENCES `elearningdb`.`apprenants` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suiviApprenant_contenuModuleForm1`
    FOREIGN KEY (`contenuModuleForm_idContenuModuleForm`)
    REFERENCES `elearningdb`.`contenuModuleForm` (`idContenuModuleForm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suiviApprenant_testsModuleForm1`
    FOREIGN KEY (`testsModuleForm_idTest`)
    REFERENCES `elearningdb`.`testsModuleForm` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`choix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`choix` (
  `idChoix` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `noteReponse` VARCHAR(45) NULL,
  `apprenants_idApprenant` INT NOT NULL,
  `propositions_idProposition` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idChoix`),
  INDEX `fk_choix_apprenants1_idx` (`apprenants_idApprenant` ASC),
  INDEX `fk_choix_propositions1_idx` (`propositions_idProposition` ASC),
  CONSTRAINT `fk_choix_apprenants1`
    FOREIGN KEY (`apprenants_idApprenant`)
    REFERENCES `elearningdb`.`apprenants` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_choix_propositions1`
    FOREIGN KEY (`propositions_idProposition`)
    REFERENCES `elearningdb`.`propositions` (`idProposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`decisionFinale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`decisionFinale` (
  `idDecisionFinale` INT NOT NULL AUTO_INCREMENT,
  `dateDecision` DATETIME NULL,
  `noteFinale` DOUBLE NULL,
  `moyenne` DOUBLE NULL,
  `mention` VARCHAR(100) NULL,
  `apprenants_idApprenant` INT NOT NULL,
  PRIMARY KEY (`idDecisionFinale`),
  INDEX `fk_decisionFinale_apprenants1_idx` (`apprenants_idApprenant` ASC),
  CONSTRAINT `fk_decisionFinale_apprenants1`
    FOREIGN KEY (`apprenants_idApprenant`)
    REFERENCES `elearningdb`.`apprenants` (`idApprenant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`administrateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`administrateur` (
  `idAdmini` INT NOT NULL AUTO_INCREMENT,
  `nomComplet` VARCHAR(150) NULL,
  `email` VARCHAR(100) NULL,
  `contact` VARCHAR(45) NULL,
  `mdp` VARCHAR(255) NULL,
  PRIMARY KEY (`idAdmini`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
