<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <base href="<?= URL; ?>">
    <title><?= SITE_NAME; ?></title>

    <link rel="stylesheet" href="<?= URL.'assets/uikit/dist/css/uikit.min.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/animate.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/aos.css' ?>">
</head>
<body>
<div class="uk-section uk-section-default uk-position-relative uk uk-height-viewport">
    <div class="uk-position-center" style="width: 400px;height: 100vh;background: #fff">
        <div>
            <h1 class="uk-text-primary uk-text-center">Panel</h1>
        </div>
        <hr class="uk-divider-icon">
        <div id="logMessage" class="uk-alert uk-alert-danger" style="display: none"></div>
        <form novalidate class="uk-position-center">
            <div class="uk-text-center">
                <h5>Connectez vous</h5>
            </div>
            <div class="">
                <label for="username" class="uk-form-label">Email</label>
                <div class="uk-inline uk-width-1-1">
                    <span class="uk-form-icon" uk-icon="icon: pencil"></span>
                    <input class="uk-input" id="username" name="username" type="email">
                </div>
            </div>
            <div class="uk-margin">
                <label for="password" class="uk-form-label">Mot de passe</label>
                <div class="uk-inline uk-width-1-1">
                    <span class="uk-form-icon" uk-icon="icon: lock"></span>
                    <input class="uk-input" type="password" id="password">
                </div>
            </div>

            <div class="uk-margin uk-text-center">
                <button type="submit" class="uk-button uk-button-primary" id="btnLog">
                    <span uk-icon="icon: login"></span> Me connecter
                </button>
            </div>
        </form>
        <div class="uk-position-bottom uk-text-center uk-height-small uk-background-muted">
            <div class="uk-text-center">
                <a href="<?= URL ?>" class="uk-icon-button" uk-icon="home"></a>
            </div>
            <div class="uk-grid uk-grid-small uk-flex uk-flex-center uk-flex-middle" uk-grid>
                <div>
                    <a href="">Mot de passe oublié ?</a><br>
                    <a href="">Créer mon compte</a>
                </div>
                <div>
                    <h1 class="uk-margin-remove"><small>Classroom</small></h1>
                    <p class="uk-margin-remove">By HIECI</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?= URL.'assets/js/jquery.min.js';?>"></script>
<script src="<?= URL.'assets/uikit/dist/js/uikit.min.js';?>"></script>
<script src="<?= URL.'assets/uikit/dist/js/uikit-icons.min.js';?>"></script>
<link rel="stylesheet" href="<?= URL.'/assets/js/aos.js' ?>">

<script src="<?= URL.'public/panel/js/log.js'; ?>"></script>
</body>
</html>