<h1 class="uk-text-primary">Cours</h1>
<div class="uk-panel">
    <ul uk-tab>
        <li class="uk-active"><a href="<?= URL.'panel/cours/liste'; ?>">Cours enregistrés</a></li>
        <li><a href="<?= URL.'panel/cours/ajout'; ?>">Ajouter un cours</a></li>
    </ul>
    <ul class="uk-switcher">
        <li>
            <div>
                <h4>Mes cours</h4>
            </div>
        </li>
        <li>
            <div>
                <h4>Nouveau cours</h4>
                
            </div>
        </li>
    </ul>
</div>
