<h1>Catalogue de cours</h1>
<div class="uk-container">

<div class="uk-grid" uk-grid>
    <div class="uk-card uk-card-secondary uk-card-body uk-width-1-4@m" uk-card>
        <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
                <li class="uk-active"><a href="<?= URL.'panel/'; ?>">TOUS LES COURS</a></li>
                <li class="uk-nav-divider"></li>
                <li class="uk-nav-header">FILTRER PAR PERIODE</li>
                <li><a href="<?= URL.''; ?>">En cours</a></li>
                <li><a href="<?= URL.''; ?>">Démarre bientôt</a></li>
<!--                <li><a href="--><?//= URL.''; ?><!--">Soumis à inscription</a></li>-->
                <li class="uk-nav-divider"></li>
                <li class="uk-nav-header">FILTRER PAR THEME</li>
                <li><a href="<?= URL.''; ?>">Programmation</a></li>
                <li><a href="<?= URL.''; ?>">Administration système</a></li>
                <li><a href="<?= URL.''; ?>">Réseaux informatiques</a></li>
                <li><a href="<?= URL.''; ?>">Sécurité informatique</a></li>
                <li><a href="<?= URL.''; ?>">Langue</a></li>
        </ul>
    </div>
    <div class="uk-width-3-4@m">
        <div class="uk-panel" uk-panel>
            <h4 class="uk-margin-remove uk-text-danger uk-text-bold">TOUS LES COURS</h4>
            <hr class="uk-divider-icon uk-margin-remove">
        </div>
        <div class="uk-grid uk-grid-divider uk-grid-match uk-grid-small uk-child-width-1-3@m" uk-grid>
            <div>
                <div class="uk-card uk-card-default uk-card-small uk-card-body">
                    <div class="uk-card-header">
                        <div class="uk-card-badge uk-label">Status</div>
                        <h3 class="uk-card-title">Cours title</h3>
                    </div>
                    <div class="uk-card-media-top">
                        <img src="<?= URL.'media/img/paper.jpg'; ?>" alt="">
                    </div>
                    <div class="uk-card-body">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio quidem 
                        illum vero commodi alias molestias eaque ducimus qui! Alias sequi maiores eveniet, 
                        </p>
                    </div>
                    <div class="uk-card-footer">
                        <div class="uk-grid uk-grid-small uk-child-width-1-2@m" uk-grid>
                            <button class="uk-button uk-button-default">Détail</button>
                            <button class="uk-button uk-button-primary">S'inscrire</button>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="uk-card uk-card-default uk-card-small uk-card-body">
                    <div class="uk-card-header">
                        <div class="uk-card-badge uk-label">Status</div>
                        <h3 class="uk-card-title">Cours title</h3>
                    </div>
                    
                    <div class="uk-card-media-top">
                        <img src="<?= URL.'media/img/paper.jpg'; ?>" alt="">
                    </div>
                    <div class="uk-card-body">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio quidem 
                        illum vero commodi alias molestias eaque ducimus qui! Alias sequi maiores eveniet, 
                        </p>
                    </div>
                    <div class="uk-card-footer">
                        <div class="uk-grid uk-grid-small uk-child-width-1-2@m" uk-grid>
                            <button class="uk-button uk-button-default">Détail</button>
                            <button class="uk-button uk-button-primary">S'inscrire</button>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="uk-card uk-card-default uk-card-small uk-card-body">
                    <div class="uk-card-header">
                        <div class="uk-card-badge uk-label">Status</div>
                        <h3 class="uk-card-title">Cours title</h3>
                    </div>
                    
                    <div class="uk-card-media-top">
                        <img src="<?= URL.'media/img/paper.jpg'; ?>" alt="">
                    </div>
                    <div class="uk-card-body">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio quidem 
                        illum vero commodi alias molestias eaque ducimus qui! Alias sequi maiores eveniet, 
                        </p>
                    </div>
                    <div class="uk-card-footer">
                        <div class="uk-grid uk-grid-small uk-child-width-1-2@m" uk-grid>
                            <button class="uk-button uk-button-default">Détail</button>
                            <button class="uk-button uk-button-primary">S'inscrire</button>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="uk-card uk-card-default uk-card-small uk-card-body">
                    <div class="uk-card-header">
                        <div class="uk-card-badge uk-label">Status</div>
                        <h3 class="uk-card-title">Cours title</h3>
                    </div>
                    
                    <div class="uk-card-media-top">
                        <img src="<?= URL.'media/img/paper.jpg'; ?>" alt="">
                    </div>
                    <div class="uk-card-body">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio quidem 
                        illum vero commodi alias molestias eaque ducimus qui! Alias sequi maiores eveniet, 
                        </p>
                    </div>
                    <div class="uk-card-footer">
                        <div class="uk-grid uk-grid-small uk-child-width-1-2@m" uk-grid>
                            <button class="uk-button uk-button-default">Détail</button>
                            <button class="uk-button uk-button-primary">S'inscrire</button>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="uk-card uk-card-default uk-card-small uk-card-body">
                    <div class="uk-card-header">
                        <div class="uk-card-badge uk-label">Status</div>
                        <h3 class="uk-card-title">Cours title</h3>
                    </div>
                    
                    <div class="uk-card-media-top">
                        <img src="<?= URL.'media/img/paper.jpg'; ?>" alt="">
                    </div>
                    <div class="uk-card-body">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio quidem 
                        illum vero commodi alias molestias eaque ducimus qui! Alias sequi maiores eveniet, 
                        </p>
                    </div>
                    <div class="uk-card-footer">
                        <div class="uk-grid uk-grid-small uk-child-width-1-2@m" uk-grid>
                            <button class="uk-button uk-button-default">Détail</button>
                            <button class="uk-button uk-button-primary">S'inscrire</button>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <div class="uk-card uk-card-default uk-card-small uk-card-body">
                    <div class="uk-card-header">
                        <div class="uk-card-badge uk-label">Status</div>
                        <h3 class="uk-card-title">Cours title</h3>
                    </div>
                    
                    <div class="uk-card-media-top">
                        <img src="<?= URL.'media/img/paper.jpg'; ?>" alt="">
                    </div>
                    <div class="uk-card-body">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio quidem 
                        illum vero commodi alias molestias eaque ducimus qui! Alias sequi maiores eveniet, 
                        </p>
                    </div>
                    <div class="uk-card-footer">
                        <div class="uk-grid uk-grid-small uk-child-width-1-2@m" uk-grid>
                            <button class="uk-button uk-button-default">Détail</button>
                            <button class="uk-button uk-button-primary">S'inscrire</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
