<div class="uk-section uk-section-muted">
    <div class="uk-container">
        <div class="uk-grid uk-grid-small uk-child-width-1-4@m">
            <div>
                <h4>HIECI MOOC</h4>
            </div>
            <div>
                <ul class="uk-list">
                    <li><a href="">Condition d'utilisation</a></li>
                    <li><a href="">Foire aux questions</a></li>
                </ul>
            </div>

            <div>
                <h4>Section Formateur</h4>
                <ul class="uk-list">
                    <li><a href="<?= URL.'panel/'; ?>">Aller au panel</a></li>
                    <li><a href="<?= URL.'panel/'; ?>">Soumettre ma candidature</a></li>
                </ul>
            </div>

            <div>
                <p>&copy;Copyright Octobre 2019</p>
                <h6>By HIECI</h6>
            </div>
        </div>
    </div>
</div>