<header class="uk-position-fixed uk-position-top uk-width-1-1@m uk-position-z-index" style="z-index: 10">
    <nav class="uk-navbar-container" uk-navbar style="background: #fff">
        <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
                <li><a href="<?= URL; ?>">HIECI CLASSROOM</a></li>
                <!--            <li><a href="--><?//= URL.'cours'; ?><!--">Cours</a></li>-->
            </ul>
        </div>
        <div class="uk-navbar-center">

        </div>
        <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
                <li><a href="<?= URL.'catalogue'; ?>" class="uk-button uk-button-small uk-button-link">Catalogue</a></li>
                <?php if(isset($_SESSION['uid']) && !empty($_SESSION['uid'])): ?>
                    <li><a href="<?= URL.'classroom/'; ?>">Aller au cours</a></li>
                    <li><a href="<?= URL.'logout'; ?>">Quitter</a></li>
                <?php elseif(isset($_SESSION['frm_uid']) && !empty($_SESSION['frm_uid'])): ?>
                    <li><a href="<?= URL.'panel/'; ?>">Espace prof</a></li>
                    <li><a href="<?= URL.'logout'; ?>">Quitter</a></li>
                <?php else: ?>
                    <li>
                        <a href="javascript:void(0);" class="uk-button uk-button-small uk-button-link">Connexion</a>
                        <div class="uk-navbar-dropdown">
                            <ul class="uk-nav uk-navbar-dropdown-nav">
                                <li><a href="<?= URL.'classroom/'; ?>">Espace Etudiant</a></li>
                                <li class="uk-nav-divider"></li>
                                <li><a href="<?= URL.'panel/'; ?>">Espace Formateur</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="<?= URL.'inscription'; ?>" class="uk-button uk-button-small uk-button-danger" style="color: #fff">Inscription</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </nav>
    <hr class="uk-margin-remove">
</header>
