<nav class="uk-navbar-container" uk-navbar>
    <div class="uk-navbar-left">
        <ul class="uk-navbar-nav">
            <li><a href="<?= URL; ?>">Accueil</a></li>
            <li><a href="<?= URL.'cours'; ?>">Cours</a></li>
        </ul>
    </div>
    <div class="uk-navbar-center"></div>
    <div class="uk-navbar-right">
        <ul class="uk-navbar-nav">
            <li><a href="<?= URL.'connexion'; ?>">Connexion</a></li>
            <li><a href="<?= URL.'inscription'; ?>">Inscription</a></li>
        </ul>
    </div>
</nav>