<h1 class="uk-text-heading uk-text-center">
    Bienvenue au MOOC du group HIECI
</h1>
<p class="uk-text-center">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam eum exercitationem hic odio officiis reprehenderit ullam ut vel? Beatae commodi eaque facere laboriosam libero magnam minima non soluta tempore vero!
</p>
<div class="uk-section uk-section-muted uk-section-small uk-height-medium uk-background-cover"
     style="background: url(<?= URL.'media/img/notebook.jpg'; ?>);background-size: 100%">

</div>

<div class="uk-section">
    <h1>Cours en avant <span uk-icon="icon: chevron-double-left"></span>
        <a href="<?= URL.'catalogue'; ?>"><small class="uk-text-danger">Consulter tout le catalogue</small></a>
        <span uk-icon="icon: chevron-double-right"></span>
    </h1>
    <div class="uk-grid uk-grid-small uk-child-width-1-2@s" uk-grid>
        <div class="uk-flex uk-flex-between uk-grid uk-grid-match uk-grid-collapse uk-margin-small-bottom" uk-grid>
            <div class="uk-width-1-2@m">
                <img src="<?= URL.'media/img/notebook.jpg'; ?>" alt="">
            </div>
            <div class="uk-width-1-2@m uk-padding-small">
                <div>
                    <b>Cours:</b>
                    <h6 class="uk-margin-remove">M310: MongoDB Security</h6>
                </div>
                <p>Status: <b class="uk-text-success">A venir</b></p>
                <a href="" class="uk-button uk-button-default uk-button-small uk-button-primary">Aperçu</a>
            </div>
        </div>
        <div class="uk-flex uk-flex-between uk-grid uk-grid-match uk-grid-collapse uk-margin-small-bottom" uk-grid>
            <div class="uk-width-1-2@m">
                <img src="<?= URL.'media/img/notebook.jpg'; ?>" alt="">
            </div>
            <div class="uk-width-1-2@m uk-padding-small">
                <div>
                    <b>Cours:</b>
                    <h6 class="uk-margin-remove">M310: MongoDB Security</h6>
                </div>
                <p>Status: <b class="uk-text-success">A venir</b></p>
                <a href="" class="uk-button uk-button-default uk-button-small uk-button-primary">Aperçu</a>
            </div>
        </div>

    </div>
</div>