<?php if(!isset($_SESSION['uid']) || $_SESSION['uid'] == ''): ?>
<div class="uk-container">
    <div class="uk-width-medium" style="margin: auto">
        <form id="loginFrm" novalidate>
            <div class="uk-text-center">
                <h5>Connectez vous</h5>
            </div>
            <div id="logMessage" class="uk-alert uk-alert-danger" style="display: none"></div>
            <div class="">
                <label for="username" class="uk-form-label">Email</label>
                <div class="uk-inline uk-width-1-1">
                    <span class="uk-form-icon" uk-icon="icon: pencil"></span>
                    <input class="uk-input" id="username" name="username" type="email">
                </div>
            </div>
            <div class="uk-margin">
                <label for="password" class="uk-form-label">Mot de passe</label>
                <div class="uk-inline uk-width-1-1">
                    <span class="uk-form-icon" uk-icon="icon: lock"></span>
                    <input class="uk-input" type="password" id="password">
                </div>
            </div>

            <div class="uk-margin uk-text-center">
                <button type="submit" class="uk-button uk-button-primary" id="btnLog">
                    <span uk-icon="icon: login"></span> Me connecter
                </button>
            </div>
        </form>
        <hr>
        <p>
            Je n'ai pas de compte, <a href="./inscription">je m'inscris</a>
        </p>
    </div>
</div>
<?php else: ?>
    <div class="uk-container uk-container-small">
        <h3 class="uk-text-center uk-text-bold">Paiement</h3>
        <div class="uk-grid uk-grid-small uk-grid-divider" uk-grid>
            <div class="uk-width-1-3">
                <h3>Mobile Money</h3>
                <ul class="uk-list">
                    <li>Orange money: xx xx xx xx</li>
                    <li>Momo (MTN Money): xx xx xx xx</li>
                    <li>Moov money: xx xx xx xx</li>
                </ul>
            </div>
            <div class="uk-width-2-3">
                <div class="uk-alert-warning" uk-alert>
                    <p>Effectuez votre dépôt sur l'un de nos compte mobile money puis entrez la référence de votre dépôt</p>                    
                </div>
                <form action="" method="post" id="frmFinishPaie">
                    <input type="hidden" name="module" id="module" value="<?= $formation->sessionNom; ?>">
                        <div class="uk-margin">
                            <select name="mode_paie" id="mode_paie" class="uk-select">
                                <option value="">------ Sélection mobible money ------</option>
                                <option value="orange">Orange Money</option>
                                <option value="mtn">Momo</option>
                                <option value="moov">Moov Money</option>
                            </select>
                        </div>
                        <div class="uk-margin">
                            <label for="reference_depot">Reférence du dépôt:</label>
                            <input type="text" id="reference_depot" class="uk-input">
                        </div>
                        <div class="uk-margin uk-text-center">
                            <button type="submit" class="uk-button uk-button-danger">Terminer</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
<?php endif; ?>

<script src="<?= URL.'public/tpl/js/main.js'; ?>"></script>
<script src="<?= URL.'public/tpl/js/login.js'; ?>"></script>