
<div class="uk-width-1-3@m " style="margin:auto">
<form>
    <fieldset class="uk-fieldset">

        <legend class="uk-legend uk-text-center">Inscription au Mooc</legend>
        <hr class="uk-divider-icon">
        <!-- <div class="uk-margin">
            <input class="uk-range " type="range" value="5" min="0" max="10" step="0.1">
        </div> -->

        <div class="uk-margin">
            <input class="uk-input" type="text" placeholder="Nom" name="nom_app" id="nom_app">
        </div>

        <div class="uk-margin">
            <input class="uk-input" type="text" placeholder="Prenom" name="prenom_app" id="prenom_app">
        </div>

        <div class="uk-margin">
            <input class="uk-input" type="text" placeholder="Pseudo"name="pseudo_app" id="pseudo_app">
        </div>

        <div class="uk-margin">
            <input class="uk-input" type="password" placeholder="Mot de passe" name="mdp_app" id="mdp_app">
        </div>

        <div class="uk-margin">
            <input class="uk-input" type="text" placeholder="Email" name="email_app" id="email_app">
        </div>

        <div class="uk-margin">
            <input class="uk-input" type="text" placeholder="Contact" name="contact_app" id="contact_app">
        </div>

    </fieldset>


   
<button type="submit" class="uk-button uk-button-primary uk-width-1-1 uk-margin-small-bottom">S'inscrire</button>




</form>




</div>