<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <base href="<?= URL; ?>">
    <title><?= SITE_NAME; ?></title>

    <link rel="stylesheet" href="<?= URL.'assets/uikit/dist/css/uikit.min.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/animate.css' ?>">
    <link rel="stylesheet" href="<?= URL.'assets/css/aos.css' ?>">

    <script src="<?= URL.'assets/js/jquery.min.js';?>"></script>
</head>
<body>
<?php require_once 'header.phtml'; ?>
    <main class="uk-margin-large-top uk-padding">
        <?= $output; ?>
    </main>
<?php require_once 'footer.phtml'; ?>

<script src="<?= URL.'assets/uikit/dist/js/uikit.min.js';?>"></script>
<script src="<?= URL.'assets/uikit/dist/js/uikit-icons.min.js';?>"></script>
<link rel="stylesheet" href="<?= URL.'/assets/js/aos.js' ?>">
</body>
</html>